import { swatchProof } from "./demo-proof";
import { assignRanks } from "./scoring";
import type { CompletedRun, Heist } from "./types";
export const PLAYER_DEFAULT_ALIAS = "Soft Hands";
const beat = (id: string, title: string, prompt: string, proofType: "photo" | "video" | "selfie", tip: string, placeName: string, x: number, y: number) => ({ id, title, prompt, proofType, tip, placeName, x, y });
export const seedHeists: Heist[] = [
  { id: "pigeon-job", title: "The Pigeon Job", alias: "Velvet Crumb", tagline: "Steal the plaza. Leave the crumbs. Tell no bird.", difficulty: 2, neighborhood: "Civic Plaza", art: "pigeon", featured: true, trending: true, nearMe: true, comedyFailAward: "Best Fail", wantedNumber: 7, createdAt: 1, published: true, beats: [
    beat("pj-1", "The Council", "Photograph the pigeon parliament on the fountain rim. They must look like they agreed to this.", "photo", "Crouch. They respect commitment.", "Fountain rim", 52, 34),
    beat("pj-2", "The Decoy", "Plant a pastry on the green bench. Photograph the crime scene before the first peck.", "photo", "Butter side up. This is non-negotiable.", "The green bench", 28, 58),
    beat("pj-3", "The Strut", "Capture one pigeon walking like it has a meeting across town. Follow. Never lead.", "video", "Keep the camera low. Dignity is the whole gag.", "Plaza tiles", 68, 62),
    beat("pj-4", "The Empty Throne", "Selfie with the empty bench after the flock lifts. Proof they left. Proof you didn't.", "selfie", "Soft smile. You are not a suspect.", "Same bench, after", 30, 78),
  ]},
  { id: "gelato-swap", title: "Midnight Gelato Swap", alias: "Cold Hands", tagline: "Two cups change coats. Nobody saw the pistachio leave.", difficulty: 3, neighborhood: "Harbor Row", art: "gelato", trending: true, nearMe: true, wantedNumber: 12, createdAt: 2, published: true, beats: [beat("gs-1", "Window Watch", "Photo the closed gelato case like it still owes you a favor.", "photo", "Reflections count as alibis.", "Harbor parlor", 40, 30), beat("gs-2", "The Switch", "Two cups, one frame. Labels must be wrong on purpose.", "photo", "Pistachio never sits on the left.", "Marble counter", 58, 48), beat("gs-3", "Walk-off", "Selfie from the alley with a clean spoon and a guilty grin.", "selfie", "Do not lick the evidence.", "Service alley", 72, 70)] },
  { id: "whisper-stack", title: "The Whisper Stack", alias: "Quiet Ink", tagline: "Reshelve three lies. Leave the truth in the wrong aisle.", difficulty: 4, neighborhood: "Civic Library", art: "library", trending: true, nearMe: false, wantedNumber: 3, createdAt: 3, published: true, beats: [beat("ws-1", "Card Catalog", "Photo a drawer left a finger-width open. No faces.", "photo", "Whisper even when you are alone.", "West stacks", 24, 28), beat("ws-2", "Wrong Aisle", "A romance novel in Reference. Proof it belongs there now.", "photo", "Ask the book for consent.", "Reference 900s", 50, 46), beat("ws-3", "Silent Exit", "Video the revolving door catching late light.", "video", "If it squeaks, that is the score.", "Marble lobby", 76, 68)] },
  { id: "fountain-caper", title: "Fountain Coin Caper", alias: "Skip Jack", tagline: "Borrow one wish. Return a better one.", difficulty: 1, neighborhood: "Memorial Circle", art: "fountain", trending: false, nearMe: true, comedyFailAward: "Legendary Fail", wantedNumber: 21, createdAt: 4, published: true, beats: [beat("fc-1", "Spot the Copper", "Photograph the brightest coin without touching the water.", "photo", "Knees dry. Pride optional.", "North basin", 48, 36), beat("fc-2", "The Better Wish", "Selfie dropping a bottle cap as if it were treasure.", "selfie", "Commit to the toss.", "South rim", 62, 64), beat("fc-3", "Dry Getaway", "Proof your socks survived. That is the whole job.", "photo", "If they didn't, log the fail.", "Steps", 30, 78)] },
];
const proofs = ["pj-1", "pj-2", "pj-3", "pj-4"].map((beatId, i) => ({ beatId, dataUrl: swatchProof(["#2a2214", "#3a2418", "#241810", "#1a1612"][i], ["The Council", "The Decoy", "The Strut", "Empty Throne"][i]), style: i % 2 ? 4 : 5, isFail: i === 3 }));
const seedBoard: CompletedRun[] = [{ id: "run-velvet", heistId: "pigeon-job", heistTitle: "The Pigeon Job", crewAlias: "Velvet Crumb", startedAt: 1, finishedAt: 1120001, elapsedMs: 1120000, proofs, styleAvg: 4.5, failAward: "Best Fail", wantedRank: 0 }];
export const seedRuns = assignRanks(seedBoard);
