import Link from "next/link";
import { DifficultyStars } from "@/components/difficulty-stars";
import { FailAwardPill } from "@/components/fail-award-pill";
import { NoirArt } from "@/components/noir-art";
import { wantedLabel } from "@/lib/utils";
import type { Heist } from "@/lib/types";
export function FeaturedHeistCard({ heist }: { heist: Heist }) {
  return <Link href={`/heist/${heist.id}`} className="block overflow-hidden rounded-2xl border border-gold/40 bg-card shadow-[0_20px_50px_rgba(0,0,0,0.35)]"><div className="relative"><NoirArt art={heist.art} className="h-48"/><div className="absolute left-3 top-3 rounded-full border border-gold/50 bg-ink/70 px-2.5 py-1 font-display text-[11px] tracking-[0.2em] text-gold uppercase">Featured job</div></div><div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-display text-[11px] tracking-[0.22em] text-bronze uppercase">Most Wanted {wantedLabel(heist.wantedNumber)}</p><h2 className="font-serif text-[2rem] leading-none text-cream italic">{heist.title}</h2></div><DifficultyStars value={heist.difficulty} size="md"/></div><p className="text-sm leading-relaxed text-cream/70">{heist.tagline}</p><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-cream/50">{heist.neighborhood}</span><span className="text-cream/25">·</span><span className="text-xs text-cream/50">Mastermind {heist.alias}</span>{heist.comedyFailAward ? <FailAwardPill award={heist.comedyFailAward}/> : null}</div><div className="flex items-center justify-between border-t border-bronze/30 pt-3"><span className="font-display text-sm tracking-[0.18em] text-gold uppercase">Open briefing</span><span className="text-xs text-cream/45">{heist.beats.length} beats</span></div></div></Link>;
}
export function HeistRow({ heist }: { heist: Heist }) {
  return <Link href={`/heist/${heist.id}`} className="flex overflow-hidden rounded-2xl border border-bronze/30 bg-card"><NoirArt art={heist.art} className="w-28 shrink-0"/><div className="flex min-w-0 flex-1 flex-col justify-center gap-1.5 p-3"><div className="flex items-center justify-between gap-2"><p className="font-display text-[10px] tracking-[0.2em] text-bronze uppercase">Wanted {wantedLabel(heist.wantedNumber)}</p><DifficultyStars value={heist.difficulty}/></div><h3 className="truncate font-serif text-xl italic text-cream">{heist.title}</h3><p className="truncate text-xs text-cream/50">{heist.neighborhood} · {heist.beats.length} beats · {heist.alias}</p>{heist.comedyFailAward ? <FailAwardPill award={heist.comedyFailAward}/> : null}</div></Link>;
}
