"use client";
import { toPng } from "html-to-image";
import { Download, Share2 } from "lucide-react";
import { useRef, useState } from "react";
import { KeyholeLogo, WaxSeal } from "@/components/keyhole-logo";
import { pickHeroProof } from "@/lib/scoring";
import type { CompletedRun, Heist } from "@/lib/types";
import { formatElapsed, wantedLabel } from "@/lib/utils";
import { Button } from "@/components/ui/button";
export function ShareCardA({ run, heist }: { run: CompletedRun; heist?: Heist }) { const hero = pickHeroProof(run.proofs); return <div className="relative h-[540px] w-[360px] overflow-hidden bg-[#0B0B0C] text-[#F2F0EA]"><div className="absolute inset-0">{hero ? <img src={hero.dataUrl} alt="" className="h-full w-full object-cover opacity-55"/> : null}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/20"/></div><div className="relative flex h-full flex-col justify-between p-6"><div className="flex items-center gap-2"><KeyholeLogo className="size-7"/><span className="font-display tracking-[0.28em] uppercase">Street Heists</span></div><div><p className="font-display text-xs tracking-[0.22em] text-[#C9A227] uppercase">A Midnight Crew picture</p><h2 className="font-serif text-5xl leading-[0.9] italic">{run.heistTitle}</h2><p className="mt-3 text-sm">Crew {run.crewAlias}{heist ? ` · ${heist.neighborhood}` : ""}</p><p>{formatElapsed(run.elapsedMs)} · Style {run.styleAvg.toFixed(1)}</p></div><div className="flex items-end justify-between"><p className="text-[11px] text-[#C9A227] uppercase">Pure make-believe. Zero real crime.</p><WaxSeal label="Seal"/></div></div></div>; }
export function ShareCardC({ run }: { run: CompletedRun }) { return <div className="h-[240px] w-[480px] bg-[#0B0B0C] p-4 text-[#F2F0EA]"><div className="flex justify-between"><span className="font-display tracking-widest uppercase">Street Heists</span><span className="text-[#C9A227]">Most Wanted {wantedLabel(run.wantedRank)}</span></div><div className="my-3 flex h-[132px] gap-2">{run.proofs.map(p => <div key={p.beatId} className="flex-1 overflow-hidden border-2 border-[#C9A227]"><img src={p.dataUrl} alt="" className="h-full w-full object-cover"/></div>)}</div><div className="flex justify-between"><span className="font-serif text-xl italic">{run.heistTitle}</span><span>{run.crewAlias} · {formatElapsed(run.elapsedMs)}</span></div></div>; }
export function ShareExports({ run, heist }: { run: CompletedRun; heist?: Heist }) { const a = useRef<HTMLDivElement>(null); const c = useRef<HTMLDivElement>(null); const [busy, setBusy] = useState<string | null>(null); async function save(which: "A" | "C") { const node = which === "A" ? a.current : c.current; if (!node) return; setBusy(which); const url = await toPng(node, { pixelRatio: 2 }); const link = document.createElement("a"); link.href = url; link.download = `street-heists-card-${which.toLowerCase()}.png`; link.click(); setBusy(null); } return <div className="space-y-5"><div className="fixed -left-[1400px]"><div ref={a}><ShareCardA run={run} heist={heist}/></div><div ref={c}><ShareCardC run={run}/></div></div><p className="font-display text-gold uppercase">Card A · Movie poster</p><div className="h-[464px] overflow-hidden"><div className="origin-top-left scale-[0.86]"><ShareCardA run={run} heist={heist}/></div></div><Button className="w-full" onClick={() => save("A")}><Share2 className="size-4"/>{busy === "A" ? "Printing…" : "Export card A"}</Button><p className="font-display text-gold uppercase">Card C · Proof strip</p><div className="h-[175px] overflow-hidden"><div className="origin-top-left scale-[0.72]"><ShareCardC run={run}/></div></div><Button variant="bronze" className="w-full" onClick={() => save("C")}><Download className="size-4"/>{busy === "C" ? "Printing…" : "Export card C"}</Button></div>; }
